### ISSUE TITLE
Not Replicated Topic alerts has no topic name in the labels

### ISSUE THREAD

**Issue by err404r** [canonical/kafka-operator#160]
Charm is exporting several alert rules to prometheus, and one of them is the rule to monitore not replicated topics.
This alerts have a tendency to trigger randomly during working, and after some discussions with the customer we want to silence it per topic based. But this is not possible, because topic name is not exported into labels list.

Also maybe we should just increase duration before alert is triggered because mostly we observe this alert on temporary bases.

**Comment by alexismosquera** [comment]
Hi team.
What is the current status of this?

**Comment by deusebio** [comment]
Yes, I can confirm that also on kafka for vm/iaas environment (revision 153) has the name of the topic and the partition number. I'm going to close the issue. Please let us know if you are still having some issues with this. Feel free to reach out to the [Data Platform room in matrix](https://matrix.to/#/#charmhub-data-platform:ubuntu.com), to get support.
