### ISSUE TITLE
Removing relation and re-relating with ZooKeeper does not work

### ISSUE THREAD

**Issue by deusebio** [canonical/kafka-operator#218]
When deploying Kafka and Zookeeper, removing the relation and re-adding the relation, not all the Kafka nodes come up healthy. Analysis of the logs suggest that non-leader are not able to authenticate to zookeeper. Indeed the `zookeeper-jaas.cfg` file on non-leader nodes keep having the old username and password. 

We provide a bundle to reproduced attached to the issue. 

## Steps to reproduce

1. juju deploy bundle.yaml
2. (wait for everything to go into a idle/active state)
3. juju remove-relation kafka zookeeper
4. juju relate kafka zookeeper

## Expected behavior

The kafka cluster comes back online healthy, with all nodes up and running. 

## Actual behavior

The non leader units report

```
snap service not running
```

## Versions

Operating system: 22.04

Juju CLI: 3.4/stable

Juju agent: 3.4.4

Charm revision: Kafka 177 and ZooKeeper 134

LXD: 5.0.3

[bundle.yaml.txt](https://github.com/user-attachments/files/16394874/bundle.yaml.txt)

**Comment by Batalex** [comment]
Closing this, as the issue could not be reproduced on newer versions, and we have integration tests for it.
