### ISSUE TITLE
Built-in alert rules

### ISSUE THREAD

**Issue by sed-i** [canonical/kafka-operator#81]
Here are just a few that I guessed could be useful to write built-in alerts for.

## Endpoint `:9100/metrics`: node-exporter
[node-exporter-metrics.txt](https://github.com/canonical/kafka-operator/files/10944541/node-exporter-metrics.txt) (151 metrics)

- [Generic node exporter rules](https://awesome-prometheus-alerts.grep.to/rules#host-and-hardware-1)

## Endpoint `:9101/metrics`: kafka
[kafka-metrics.txt](https://github.com/canonical/kafka-operator/files/10944506/kafka-metrics.txt) (222 metrics)

- Generic cpu, fds, mem, jvm metrics
- [Generic kafka rules](https://awesome-prometheus-alerts.grep.to/rules#kafka)
- Network
  - `kafka_network_requestmetrics_totaltimems`, `kafka_network_requestmetrics_remotetimems`, `kafka_network_requestmetrics_localtimems`, `kafka_network_requestmetrics_requestbytes` - historgrams for many different types of requests (JoinGroup, LeaveGroup, ElectLeaders, etc.)
  - `kafka_controller_kafkacontroller_globalpartitioncount`
  - `kafka_server_socketservermetrics_connection_creation_rate` - The number of new connections established per second
  - `kafka_server_socketservermetrics_request_rate` - The number of requests sent per second`
- DoS-related
  - `kafka_server_socketservermetrics_failed_reauthentication_rate` - The number of failed re-authentication of connections per second
  - `kafka_server_socketservermetrics_successful_authentication_rate` - The number of connections with successful authentication per second
- Zookeeper related
  - `kafka_security_aclauthorizer_zookeeperdisconnectspersec`
  - `kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms`

**Comment by sed-i** [comment]
Apparently [config files in the snap](https://github.com/canonical/charmed-kafka-snap/tree/main/snap/local/opt/kafka/default-config) influence on what/how (?) metrics are rendered.

**Comment by zmraul** [comment]
Hi @sed-i. The yaml on the snap are specific to JMX exporter, which is packed with the snap itself. Those configs are taken from the examples from [JMX exporter repo](https://github.com/prometheus/jmx_exporter/tree/main/example_configs).

**Comment by deusebio** [comment]
PR #110 has addressed to create and provide some basic, sensible defautls for alerning rules, which should close this issue
